---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: scheduler
    run_list:
      - recipe[aurora::scheduler]
    attributes:

  - name: slave
    run_list:
      - recipe[aurora::slave]
